import {ArrowUpRight, Github, Linkedin, Mail, Smartphone, Code2, Database, Layers3} from "lucide-react";

const projects=[
{number:"01",title:"Adashe Mobile",category:"Fintech · Mobile",description:"A mobile fintech platform for savings, withdrawals, loans, transactions and agent operations.",stack:["React Native","TypeScript","REST APIs","Fintech"],featured:true},
{number:"02",title:"Football App",category:"Android · Throwback",description:"A native Android football application built around 2021/2022 with predictions, football information, authentication and a Firebase data layer.",stack:["Kotlin","Android","Firebase Firestore","OAuth"],featured:false},
{number:"03",title:"More Work",category:"Coming soon",description:"A curated case study for another product or engineering project will be added here.",stack:["Project","Case Study"],featured:false}
];
const skills=[["Mobile","React Native · Android · Kotlin",Smartphone],["Languages","TypeScript · JavaScript · Kotlin",Code2],["Backend & Data","REST APIs · Firebase · Firestore",Database],["Engineering","Git · GitHub · API integration · UI architecture",Layers3]];

export default function Home(){return <main>
<nav className="glass sticky top-0 z-50 border-b border-white/10"><div className="container flex h-16 items-center justify-between"><a href="#" className="font-bold">AJ<span className="text-cyan-400">.</span></a><div className="hidden gap-7 text-sm text-slate-300 sm:flex"><a href="#work">Work</a><a href="#experience">Experience</a><a href="#about">About</a><a href="#contact">Contact</a></div><a href="#contact" className="rounded-full border border-white/15 px-4 py-2 text-sm font-semibold">Let&apos;s talk</a></div></nav>

<section className="grid-bg"><div className="container flex min-h-[650px] flex-col justify-center py-24">
<p className="mb-5 text-sm font-semibold uppercase tracking-[.25em] text-cyan-400">Mobile Engineer · Fintech · Product</p>
<h1 className="max-w-4xl text-5xl font-bold leading-[1.03] sm:text-7xl">I build mobile products that make complex workflows feel simple.</h1>
<p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">I&apos;m Abraham Jonathan, a mobile engineer focused on React Native, TypeScript and Kotlin. I build practical products across fintech, payments, savings and everyday mobile experiences.</p>
<div className="mt-9 flex flex-wrap gap-3"><a href="#work" className="inline-flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-3 font-bold text-slate-950">View my work <ArrowUpRight size={17}/></a><a href="#contact" className="rounded-full border border-white/15 px-5 py-3 font-bold">Contact me</a></div>
<div className="mt-16 flex flex-wrap gap-x-8 gap-y-3 text-sm text-slate-500"><span>React Native</span><span>TypeScript</span><span>Kotlin</span><span>Firebase</span><span>REST APIs</span></div>
</div></section>

<section id="work" className="container py-24"><div className="mb-10"><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Selected work</p><h2 className="mt-3 text-4xl font-bold">Things I&apos;ve built</h2><p className="mt-3 max-w-2xl text-slate-400">A few projects that show how my work has evolved from native Android development into modern fintech-focused mobile engineering.</p></div>
<div className="grid gap-5 lg:grid-cols-2">{projects.map(p=><article key={p.number} className={`group rounded-3xl border border-white/10 bg-white/[.025] p-7 transition hover:-translate-y-1 ${p.featured?"lg:col-span-2":""}`}><div className="flex justify-between"><span className="text-sm font-semibold text-cyan-400">{p.number}</span><ArrowUpRight className="text-slate-600" size={22}/></div><p className="mt-10 text-sm font-semibold text-slate-500">{p.category}</p><h3 className="mt-2 text-3xl font-bold">{p.title}</h3><p className="mt-4 max-w-2xl leading-7 text-slate-400">{p.description}</p><div className="mt-6 flex flex-wrap gap-2">{p.stack.map(t=><span key={t} className="rounded-full bg-white/5 px-3 py-1.5 text-xs text-slate-300">{t}</span>)}</div><div className="mt-8 text-sm font-semibold text-cyan-300">Case study coming with screenshots →</div></article>)}</div></section>

<section id="experience" className="border-y border-white/10 bg-white/[.015]"><div className="container py-24"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Experience</p><h2 className="mt-3 text-4xl font-bold">Building for real users.</h2></div><div className="border-l border-cyan-400/30 pl-6"><p className="text-sm text-cyan-300">Fintech · Mobile Engineering</p><h3 className="mt-2 text-2xl font-bold">Mobile Engineer</h3><p className="mt-4 leading-7 text-slate-400">Working on mobile workflows that support savings, withdrawals, contributions, loans, transactions, authentication and agent operations. Focused on turning product requirements into reliable, intuitive mobile experiences.</p></div></div></div></section>

<section id="about" className="container py-24"><div className="grid gap-14 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">About</p><h2 className="mt-3 text-4xl font-bold">Engineer first. Product minded.</h2></div><div className="text-lg leading-8 text-slate-400"><p>I&apos;m a Mobile Engineer focused on building reliable, user-friendly applications with React Native, TypeScript and Kotlin.</p><p className="mt-5">My experience spans fintech products, savings systems, payment workflows, authentication, API integrations and role-based mobile experiences.</p><p className="mt-5">I enjoy taking complex product requirements and turning them into simple experiences that people can actually use.</p></div></div>
<div className="mt-16 grid gap-4 sm:grid-cols-2">{skills.map(([title,detail,Icon])=>{const I=Icon as React.ComponentType<{size?:number;className?:string}>;return <div key={title as string} className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><I className="text-cyan-400" size={22}/><h3 className="mt-5 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{detail as string}</p></div>})}</div></section>

<section id="contact" className="container pb-24"><div className="rounded-3xl border border-cyan-400/20 bg-cyan-400/[.06] p-8 sm:p-12"><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Contact</p><h2 className="mt-3 max-w-2xl text-4xl font-bold sm:text-5xl">Have a product that needs to be built?</h2><p className="mt-5 max-w-xl leading-7 text-slate-400">I&apos;m open to conversations about mobile engineering, fintech products and interesting software projects.</p><div className="mt-8 flex flex-wrap gap-3"><a href="mailto:your.email@example.com" className="inline-flex items-center gap-2 rounded-full bg-cyan-400 px-5 py-3 font-bold text-slate-950"><Mail size={17}/> Email me</a><a href="https://github.com/LegendAb3" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 font-bold"><Github size={17}/> GitHub</a><a href="https://www.linkedin.com/in/abraham-jonathan-8a1300228/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 font-bold"><Linkedin size={17}/> LinkedIn</a></div></div></section>
<footer className="border-t border-white/10"><div className="container flex flex-col gap-3 py-8 text-sm text-slate-500 sm:flex-row sm:justify-between"><span>© 2026 Abraham Jonathan. Built with Next.js & TypeScript.</span><span>Mobile Engineer · Nigeria</span></div></footer>
</main>}